### PR TITLE
Disable remote methods by alias

### PR DESCRIPTION
**Pull request by Overdrivr**
### Description
Backport of #385 

#### Related issues

- strongloop/loopback#1936

### Checklist

- [x] New tests added
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
The change in `lib` looks like a straightforward backport of the change from the master, which is good! I'll leave the detailed review to @gunjpan though.

@Overdrivr could you please rebase your patch on top of the latest `2.x` branch to satisfy the "PR Linter" check, which is currently failing?

**Comment by Overdrivr** [comment]
@bajtos @gunjpan Rebase done and all checks passing, ready for review

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Comment by gunjpan** [comment]
@bajtos : It was straight forward backport, but couldn't get to review due to priorities. Thank you for chiming in :smiley:

**Pull request merged**
