### PR TITLE
fix: Timestamps not converted to Date anymore #238

### PR DESCRIPTION
**Pull request by kflip**
Signed-off-by: Philipp Kinschel <p.kinschel@nousguide.com>

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@kflip thank you for the pull request. Please add a test case to verify your implementation and prevent regressions in the future.

@raymondfeng @ritch you are more familiar with type coercion than I am, could you PTAL at this patch?

**Comment by bajtos** [comment]
Closing in favour of #349

**Pull request closed without merging**
