### PR TITLE
Stringify query params which are objects as JSON [2.x]

### PR DESCRIPTION
**Pull request by horiaradu**
This is a backport of this PR: https://github.com/strongloop/strong-remoting/pull/325. I've cherrypicked the commit and so I've added the refactorings which were made in the test file as well.

@gunjpan - check it out :)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by gunjpan** [comment]
@slnode ok to test

**Comment by gunjpan** [comment]
@horiaradu : Change LGTM. Could you please update commit message to say: `backport of PR#325`
For example, PTAL at this: https://github.com/strongloop/loopback/pull/2782/commits

**Comment by gunjpan** [comment]
@horiaradu : Thank you for updating the commit message, but now it breaks the CI with: 
```
Linting commit logs
**
**  1 problems found:
**    2323ddc - Stringify query params which are objects as JSON [2: First line should be 50 characters or less (saw 54)
```

Also, `backport of #<PR number>` should be a PR #325, instead of the issue where  it was reported as bug. 
Could you please fix it. Thank you.

**Comment by gunjpan** [comment]
@horiaradu: Landed. Thank you for the PR and keeping up with change requests.

**Pull request merged**
