### PR TITLE
Set 302 status code if response has Location header

### PR DESCRIPTION
**Pull request by umbrella-ivan-zhukov**
for loopback issue strongloop/loopback#1065

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@umbrella-ivan-zhukov thank you for the pull request. Please add a unit-test to verify that the implementation works as intended and to show how is this intended to be use.

I don't understand one thing: since the Location header was already set, why cannot the code which is changing this header also change the status code?

Perhaps the following implementation would be more correct?

```js
// in the "no content/data" branch
if (res.statusCode === 200) 
  res.statusCode = 204;
```

**Comment by umbrella-ivan-zhukov** [comment]
@bajtos , yes you're right. I'll push update to loopback PR.
But I couldn't find "no content/data" branch. Should I create it?

**Comment by bajtos** [comment]
> But I couldn't find "no content/data" branch. Should I create it?

Let me explain myself more clearly. I meant that my code above should be in the "else" branch on lines 375-379, i.e. just add the if statement before the line `res.statusCode = 204`.

Does it make more sense now?

**Comment by umbrella-ivan-zhukov** [comment]
Updated the code.
I don't have time for test, but I'll add one this weekend.

**Comment by ritch** [comment]
I'm going to close this since the change is only 3 lines and is missing a test. I'll create an issue to track this though. Please open another pull request with the correct title, test, and changes.

**Comment by ritch** [comment]
See https://github.com/strongloop/strong-remoting/issues/175

**Pull request closed without merging**
