### PR TITLE
Fixes the test/streams.js test

### PR DESCRIPTION
**Pull request by jorrit**
Broken since f01b8a6ba0b157f3e6562d11158bc3050a75d61a

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jorrit** [comment]
The patch is not yet finished, I need to add uri encoding for the pameters.

**Comment by jorrit** [comment]
It is finished, I squashed the two commits.

**Comment by jorrit** [comment]
The waiting label can be removed.

**Comment by rmg** [comment]
ok to test

**Comment by bajtos** [comment]
@ritch you were working on the stream support in strong-remoting recently, thus I think you are the best person to review this patch?

**Comment by bajtos** [comment]
@jorrit sorry for the long delay in our review process. Are you still keen to get this patch finished?

**Comment by bajtos** [comment]
Actually, I am quite puzzled by this. AFAICT, all tests are passing on the current master, which makes me think this patch is no longer relevant.

@jorrit @ritch thoughts?

**Comment by jorrit** [comment]
I think the node api has changed. At the time I created the PR, node 0.12 just changed the api of fs.createReadStream so the second argument was  an object instead of a string. I recall that this caused the problem that led me to create the PR. However, when looking at the docs of the current node version, it seems that both a string and an object are allowed. So this PR is no longer needed.

**Pull request closed without merging**
