### PR TITLE
Fix issue with serialization

### PR DESCRIPTION
**Pull request by thaiat**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by gunjpan** [comment]
@slnode ok to test

**Comment by gunjpan** [comment]
@thaiat : Thank you for your pull request. Back porting of #325 will address this issue, which is almost ready to land. Thus, closing in favor of #325.

For future reference, please add test cases along with your fix to get started with PR review process. See the [code contribution guidelines](http://loopback.io/doc/en/contrib/code-contrib.html#submitting-a-pull-request).

**Pull request closed without merging**
