### PR TITLE
translation return for Q4 drop1

### PR DESCRIPTION
**Pull request by candytangnb**
translation return for Q4 drop1

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@candytangnb thank you for the pull request. Before we can land it, we need you to sign our CLA here: https://cla.strongloop.com/agreements/strongloop/strong-remoting 

@rmg I assume @candytangnb is from IBM, could you please check why our CLA tool did not recognize this account? Is it expected that IBMers have to sign our own CLA too?

**Comment by bajtos** [comment]
@slnode ok to test

**Pull request merged**
