### PR TITLE
Close server stream once event-stream consumer disconnects

### PR DESCRIPTION
**Pull request by kraman**
Connect to strongloop-internal/scrum-nodeops#945

### CODE REVIEW

**Comment by kraman** [comment]
Based on https://nodejs.org/api/http.html#http_class_http_serverresponse looks like there is no `end` event on http response objects.

**Comment by kraman** [comment]
@ritch Looks like tests are failing for unrelated reasons.

**Comment by bajtos** [comment]
@kraman could you please add a unit-test to cover this change? I think it's really important to have an automated test in place, considering the uncertainty about the correctness of the implementation.

@piscisaureus could you perhaps take a look and let us know if we are doing this correctly? The idea is to detect when the browser client closes our long-living HTTP response stream, so that we can stop producing data that would be discarded.

**Comment by kraman** [comment]
@ritch pointed out that this is not the correct place to close the stream. It should be closed by the method that creates/manages the stream.

**Pull request closed without merging**
