### PR TITLE
adding testcase for passing remoting options

### PR DESCRIPTION
**Pull request by azatoth**
See #328
cc @bajtos

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by azatoth** [comment]
re #328

**Comment by bajtos** [comment]
The test-case does not make sense, see https://github.com/strongloop/strong-remoting/issues/328#issuecomment-244934914.

**Pull request closed without merging**
