### PR TITLE
Set to no compression when using change stream

### PR DESCRIPTION
**Pull request by 0candy**
Connect to strongloop/angular-live-set#10

Backport of #294 to 2.x

### CODE REVIEW

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by bajtos** [comment]
The changes are the same as in #294, aren't they?

I am proposing to reword the commit message a bit. There is no need to mention this is a backport to 2.x, that should be obvious from the fact that the commit will be landed on 2.x

```
Set to no compression when using change stream

[back-port of #294]
```

**Comment by bajtos** [comment]
LGTM

**Pull request merged**
