### PR TITLE
Fix issue #251, now default responses are application/json

### PR DESCRIPTION
**Pull request by jaime-franco**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
Thanks for the patch. It would be nice to add a test case to cover `*/*`.

**Comment by raymondfeng** [comment]
@bajtos or @ritch Can you review?

**Comment by bajtos** [comment]
:+1:

**Pull request merged**
