### PR TITLE
Handle array of errors.

### PR DESCRIPTION
**Pull request by richardpringle**
Connect to strongloop/loopback#2123

backport from strongloop/strong-remoting#289

### CODE REVIEW

**Comment by richardpringle** [comment]
@bajtos I believe this is okay to merge as I already merged the change on master, but could you just take one last look?

I am very reluctant to merge anything that doesn't pass CI

**Comment by bajtos** [comment]
> @richardpringle wants to merge 1 commit into 2.x-latest from 2.x-handle-error-array 

I am afraid you chose a wrong branch, all back-ports should target `2.x`.

**Comment by bajtos** [comment]
Also your code does not pass `npm test` due to linting errors, see e.g. Travis output.

**Comment by bajtos** [comment]
@richardpringle please create a new pull request targeting `2.x`, this pull request can be closed.

**Pull request closed without merging**
