### PR TITLE
Fix query string to have null

### PR DESCRIPTION
**Pull request by kobaska**
Fix to allow query string to have null. At the moment doing a find such as below would not work as qs.stringify function would remove the null from the query.

`SomeModel.find({where: {name: null}});`

Instead using JSON.stringify with encodeURI

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
Please note In LB3.x we have worked on coercion and made both conversion and coercion more strict. null value is accepted only for "object", "array" and "any". 
I see you sent this PR against `2.x`. Could you please add test to verify the changes.

**Comment by horiaradu** [comment]
I think this will be fixed with: https://github.com/strongloop/strong-remoting/pull/325

**Comment by gunjpan** [comment]
@kobaska : Thank you for your pull request. PR# 325, as mentioned by @horiaradu, addresses the same issue and it is ready to land. 

Re. your PR, please see the comments here: https://github.com/strongloop/strong-remoting/pull/325#issuecomment-256615491

For future reference, please add test cases along with your code to get the PR review started. See the code contribution guidelines for LoopBack [here](http://loopback.io/doc/en/contrib/code-contrib.html#submitting-a-pull-request).

Closing in favor of #325.

**Comment by gunjpan** [comment]
cc/ @Amir-61

**Comment by kobaska** [comment]
@gunjpan Yep will do, thanks :)

**Pull request closed without merging**
